"""
Django settings for TrainK project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#hzqu*0-tby7iyvberwew29vv^c_b(*w-zux+f73hcqv9-xf53'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
INTERNAL_IPS = ('127.0.0.1', '192.168.1.237', '192.168.1.101')

ALLOWED_HOSTS = ['tra.ink', 'localhost', '192.168.1.101', '192.168.1.10', 'home.zhangzhixing.cn']
SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'django_celery_beat',

    'webpack_loader',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',

    'user',
    'info',
    'ticket',
    'trip',
    'scrape',

    'baton.autodiscover',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'TrainK.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TrainK.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'TrainK',
        'USER': 'TrainK',
        'PASSWORD': 'Braungardt4365',
        'HOST': 'localhost',
        'PORT': '',
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtpdm.aliyun.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'notification@robot.tra.ink'
EMAIL_HOST_PASSWORD = 'aB7EZRVqo0Kbl4b3UOaM'
EMAIL_USE_SSL = True

DEFAULT_FROM_EMAIL = 'TrainK <notification@robot.tra.ink>'
SERVER_EMAIL = 'TrainK <notification@robot.tra.ink>'

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache' if DEBUG else 'redis_cache.RedisCache',
        'LOCATION': 'localhost:6379',
        'OPTIONS': {
            'DB': 0,
            'PASSWORD': 'Braungardt4365',
        },
    },
}
STATIC_URL = '/web/'
STATIC_ROOT = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'dist'),
)

if not DEBUG:
    STATICFILES_STORAGE = 'aliyun_oss2_storage.backends.AliyunStaticStorage'
    DEFAULT_FILE_STORAGE = 'aliyun_oss2_storage.backends.AliyunMediaStorage'
    ACCESS_KEY_ID = "LTAIP3L1SzIaldrp"
    ACCESS_KEY_SECRET = "hUf7QPw1TL7tM18QfMw74fpRCSo5G8"
    END_POINT = "oss-cn-hangzhou.aliyuncs.com"  # OSS存储节点
    BUCKET_NAME = "traink"
    ALIYUN_OSS_CNAME = "https://static.tra.ink"
    BUCKET_ACL_TYPE = "public-read"  # private, public-read, public-read-write


BATON = {
    'SITE_HEADER': 'TrainK Admin',
    'SITE_TITLE': 'TrainK',
    'INDEX_TITLE': 'Site administration',
    'SUPPORT_HREF': '',
    'COPYRIGHT': 'Copyright © 2017 <a href="//begin.studio">begin Studio</a>', # noqa
    'POWERED_BY': '<a href="https://www.otto.to.it">Otto srl</a>',
    'MENU': (
        {'type': 'title', 'label': 'Basic', 'apps': ('sites', )},
        {'type': 'model', 'label': 'Sites', 'name': 'site', 'app': 'sites'},
        {'type': 'app', 'name': 'django_celery_beat', 'label': 'Periodic Tasks', 'icon': 'fa fa-lock'},

        {'type': 'title', 'label': 'Users', 'apps': ('auth', )},
        {'type': 'app', 'name': 'auth', 'label': 'Authentication', 'icon': 'fa fa-lock'},
        {'type': 'model', 'label': 'Tokens', 'name': 'token', 'app': 'authtoken', 'icon': 'fa fa-envelope'},
        {'type': 'app', 'name': 'socialaccount', 'label': 'Social Auth', 'icon': 'fa fa-weibo'},
        {'type': 'model', 'label': 'Emails', 'name': 'emailaddress', 'app': 'account', 'icon': 'fa fa-envelope'},

        {'type': 'title', 'label': 'Info', 'apps': ('info', )},
        {'type': 'app', 'name': 'info', 'label': 'Train Info', 'icon': 'fa fa-info'},
        {'type': 'free', 'label': 'Custom Link', 'url': '/admin/tasks'},
    ),
}


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.TemplateHTMLRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.AdminRenderer',
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',
        'user': '30/minute'
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_METADATA_CLASS': 'rest_framework.metadata.SimpleMetadata',
}
OLD_PASSWORD_FIELD_ENABLED = True
LOGIN_REDIRECT_URL = '/user/'
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_SIGNUP_FORM_CLASS = 'user.forms.SignupForm'
ACCOUNT_FORMS = {
    'login': 'user.forms.LoginForm'
}
REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'user.serializers.UserDetailsSerializer'
}

CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_FAIL_SILENTLY = not DEBUG

_WEBPACK_STAT_FILE_PATH = 'build/webpack-stats.dev.json' if DEBUG else 'build/webpack-stats.prod.json'
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'dist/',
        'STATS_FILE': os.path.join(BASE_DIR, _WEBPACK_STAT_FILE_PATH),
    }
}

CELERY_worker_hijack_root_logger = False
CELERY_ENABLE_UTC = False
