# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('telecode', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
