# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 09:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.DurationField(blank=True)),
                ('arrivalTime', models.DurationField(blank=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('telecode', models.CharField(max_length=50)),
                ('stops', models.ManyToManyField(related_name='train', to='api.Stop')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='stops',
            field=models.ManyToManyField(related_name='record', to='api.Stop'),
        ),
        migrations.AddField(
            model_name='record',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Train'),
        ),
    ]
