# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171106_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='arrivalTime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='departureTime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
