# Generated by Django 2.0 on 2017-12-30 07:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('departureTime', models.DateTimeField()),
                ('departureTimeAnticipated', models.BooleanField()),
                ('arrivalTime', models.DateTimeField()),
                ('arrivalTimeAnticipated', models.BooleanField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureDate', models.DateField()),
                ('stops', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('telecode', models.CharField(blank=True, max_length=3)),
                ('abbreviation', models.CharField(max_length=10)),
                ('spell', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('telecode', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('stops', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('since', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='info.Train'),
        ),
        migrations.RunSQL("""
            CREATE OR REPLACE VIEW info_stop AS
            SELECT
                info_record.id || '_' || ordinality-1 AS id,
                info_record.id AS record_id,
                ordinality-1 AS index,
                ("departureDate" + "arrivalTime") AT TIME ZONE 'CCT' AS "arrivalTime",
                "arrivalTimeAnticipated",
                ("departureDate" + "departureTime") AT TIME ZONE 'CCT' AS "departureTime",
                "departureTimeAnticipated"
            FROM info_record, ROWS FROM ( jsonb_to_recordset(stops) AS (
                "departureTime" interval,
                "departureTimeAnticipated" boolean,
                "arrivalTime" interval,
                "arrivalTimeAnticipated" boolean
            )) WITH ORDINALITY
        """),
    ]
